package com.space.browser;

import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.zip.*;

/** Deterministic formatting, bounded decoding and portable HAR interchange. */
final class NetworkFormats {
    static final String[] DECODERS={"Auto","UTF-8","ISO-8859-1","GBK","Base64","URL","JSON","JWT","Form","gzip","deflate","Chunked","Binary strings"};
    static final int DISPLAY_LIMIT=128*1024;
    static String size(long n){return n<1024?n+" B":n<1048576?String.format(Locale.US,"%.1f kB",n/1024d):String.format(Locale.US,"%.2f MB",n/1048576d);}
    static String header(Map<String,String> h,String name){for(Map.Entry<String,String> e:h.entrySet())if(e.getKey().equalsIgnoreCase(name))return e.getValue();return "";}
    static boolean binary(byte[] b,String mime){if(mime.startsWith("image/")||mime.contains("font")||mime.contains("protobuf")||mime.startsWith("audio/")||mime.startsWith("video/"))return true;int controls=0;for(int i=0;i<Math.min(b.length,2048);i++){int c=b[i]&255;if(c==0)return true;if(c<9||c>13&&c<32)controls++;}return controls>Math.min(b.length,2048)/20;}
    static byte[] read(InputStream in,int max) throws IOException {ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){if(out.size()+n>max)throw new IOException("Body exceeds "+size(max)+" limit");out.write(b,0,n);}return out.toByteArray();}
    static String text(byte[] b,String contentType,boolean alreadyDecoded){String charset="UTF-8";if(!alreadyDecoded){java.util.regex.Matcher m=java.util.regex.Pattern.compile("charset=[\"']?([^;\\s\"']+)",2).matcher(contentType);if(m.find())charset=m.group(1);}try{return new String(b,Charset.forName(charset));}catch(Exception e){return new String(b,StandardCharsets.UTF_8);}}
    static String body(NetworkRecord r,boolean request,boolean decode,String decoder){
        byte[] bytes=request?r.requestBody:r.responseBody;String mime=header(request?r.requestHeaders:r.responseHeaders,"Content-Type");if(mime.isEmpty()&&!request)mime=r.mime;
        String note=request?r.requestBodyNote:r.responseBodyNote;
        if(bytes.length==0)return (request?(r.hasPostData?"Request body unavailable":"No request body"):"No captured response body")+(note.isEmpty()?"":"\n\n"+note);
        try{
            String value=text(bytes,mime,!request&&r.browserDecoded);
            if(decode){
                String chosen=decoder;
                if(chosen.equals("Auto")){
                    if(bytes.length>2&&(bytes[0]&255)==31&&(bytes[1]&255)==139)chosen="gzip";
                    else if(mime.contains("x-www-form-urlencoded"))chosen="Form";
                    else if(value.trim().startsWith("{")||value.trim().startsWith("["))chosen="JSON";
                }
                switch(chosen){
                    case "UTF-8":case "ISO-8859-1":case "GBK":value=new String(bytes,Charset.forName(chosen));break;
                    case "Base64":value=new String(Base64.getMimeDecoder().decode(value.trim()),StandardCharsets.UTF_8);break;
                    case "URL":value=URLDecoder.decode(value,"UTF-8");break;
                    case "JSON":value=pretty(value);break;
                    case "JWT":String[] parts=value.trim().split("\\.");if(parts.length!=3)throw new IOException("Expected three JWT sections");value="HEADER (signature not verified)\n"+pretty(new String(Base64.getUrlDecoder().decode(parts[0]),StandardCharsets.UTF_8))+"\n\nPAYLOAD\n"+pretty(new String(Base64.getUrlDecoder().decode(parts[1]),StandardCharsets.UTF_8));break;
                    case "Form":StringBuilder fields=new StringBuilder();for(String field:value.split("&")){String[] pair=field.split("=",2);fields.append(URLDecoder.decode(pair[0],"UTF-8")).append("  =  ").append(pair.length>1?URLDecoder.decode(pair[1],"UTF-8"):"").append('\n');}value=fields.toString();break;
                    case "gzip":try(InputStream in=new GZIPInputStream(new ByteArrayInputStream(bytes))){value=text(read(in,NetworkRecorder.BODY_LIMIT),mime,false);}break;
                    case "deflate":try(InputStream in=new InflaterInputStream(new ByteArrayInputStream(bytes))){value=text(read(in,NetworkRecorder.BODY_LIMIT),mime,false);}break;
                    case "Chunked":value=text(dechunk(bytes),mime,false);break;
                    case "Binary strings":value=strings(bytes);break;
                    default:if(binary(bytes,mime))return "Binary data · "+mime+" · "+size(bytes.length)+"\n\nUse Hex for bytes or Binary strings for embedded text. Images have a preview below. Font files cannot be decoded into readable prose.\n\n"+hex(bytes);break;
                }
                return "Decoded: "+chosen+(r.browserDecoded&&!request?" · WebView already removed transfer compression":"")+"\n\n"+value+(note.isEmpty()?"":"\n\n["+note+"]");
            }
            return binary(bytes,mime)?"Binary data · use Hex or Decode\n\n"+hex(bytes):value+(note.isEmpty()?"":"\n\n["+note+"]");
        }catch(Exception e){return "Decode failed: "+e.getMessage()+"\nOriginal bytes (hex):\n\n"+hex(bytes);}
    }
    static String pretty(String s) throws JSONException {Object o=new JSONTokener(s).nextValue();return o instanceof JSONObject?((JSONObject)o).toString(2):o instanceof JSONArray?((JSONArray)o).toString(2):String.valueOf(o);}
    static byte[] dechunk(byte[] bytes) throws IOException {ByteArrayInputStream in=new ByteArrayInputStream(bytes);ByteArrayOutputStream out=new ByteArrayOutputStream();while(true){StringBuilder line=new StringBuilder();int c;while((c=in.read())!=-1&&c!='\n'){if(c!='\r')line.append((char)c);if(line.length()>100)throw new IOException("Invalid chunk header");}int n;try{n=Integer.parseInt(line.toString().split(";",2)[0].trim(),16);}catch(Exception e){throw new IOException("Invalid chunk length");}if(n==0)return out.toByteArray();if(n<0||n>in.available()||out.size()+n>NetworkRecorder.BODY_LIMIT)throw new IOException("Invalid or oversized chunk");byte[] b=new byte[n];if(in.read(b)!=n)throw new EOFException();out.write(b);if(in.read()!=13||in.read()!=10)throw new IOException("Missing chunk terminator");}}
    static String hex(byte[] b){StringBuilder out=new StringBuilder();int max=Math.min(b.length,32768);for(int i=0;i<max;i+=16){out.append(String.format(Locale.US,"%06x  ",i));for(int j=0;j<16;j++)out.append(i+j<max?String.format(Locale.US,"%02x ",b[i+j]&255):"   ");out.append(" ");for(int j=i;j<Math.min(i+16,max);j++){int c=b[j]&255;out.append(c>=32&&c<127?(char)c:'.');}out.append('\n');}if(b.length>max)out.append("\nHex preview truncated. Save body to export every retained byte.");return out.toString();}
    static String strings(byte[] bytes){StringBuilder out=new StringBuilder(),run=new StringBuilder();for(byte b:bytes){int c=b&255;if(c>=32&&c<127)run.append((char)c);else{if(run.length()>=4)out.append(run).append('\n');run.setLength(0);}if(out.length()>DISPLAY_LIMIT)break;}if(run.length()>=4)out.append(run);return "Printable strings (not a schema-aware protobuf decoder)\n\n"+out;}
    static String raw(NetworkRecord r,boolean request){return "Browser representation — not exact compressed HTTP/2 or HTTP/3 wire bytes\n\n"+(request?r.method+" "+r.url+"\n"+NetworkRecord.headers(r.requestHeaders):r.responseText())+"\n\n"+body(r,request,false,"Auto");}
    static String all(NetworkRecord r){return "URL: "+r.url+"\n\nREQUEST\n"+r.requestText()+"\n\nRESPONSE\n"+r.responseText()+"\n\n"+body(r,false,true,"Auto");}
    static boolean matches(NetworkRecord r,String q){return q.isEmpty()||(r.url+"\n"+r.method+"\n"+r.status+"\n"+r.type+"\n"+NetworkRecord.headers(r.requestHeaders)+NetworkRecord.headers(r.responseHeaders)+body(r,true,true,"Auto")+body(r,false,true,"Auto")).toLowerCase(Locale.ROOT).contains(q.toLowerCase(Locale.ROOT));}
    static String quote(String s){return "'"+s.replace("'","'\"'\"'")+"'";}
    static String curl(NetworkRecord r){StringBuilder s=new StringBuilder("curl --request ").append(quote(r.method)).append(" ").append(quote(r.url));for(Map.Entry<String,String> h:r.requestHeaders.entrySet())if(!h.getKey().startsWith(":"))s.append(" \\\n  --header ").append(quote(h.getKey()+": "+h.getValue()));if(r.requestBody.length>0)s.append(" \\\n  --data-binary ").append(quote(new String(r.requestBody,StandardCharsets.UTF_8)));return s.toString();}
    static String fetch(NetworkRecord r){return "fetch("+JSONObject.quote(r.url)+", {\n  method: "+JSONObject.quote(r.method)+",\n  headers: "+new JSONObject(r.requestHeaders)+(r.requestBody.length==0?"":",\n  body: "+JSONObject.quote(new String(r.requestBody,StandardCharsets.UTF_8)))+"\n});\n// Browsers control forbidden headers; Cookie and User-Agent may differ.";}
    static String python(NetworkRecord r){return "import requests\nresponse = requests.request("+JSONObject.quote(r.method)+", "+JSONObject.quote(r.url)+", headers="+new JSONObject(r.requestHeaders)+", data="+JSONObject.quote(new String(r.requestBody,StandardCharsets.UTF_8))+", timeout=30)\nprint(response.status_code, response.text)";}
    static String masked(String text){return text.replaceAll("(?im)^(cookie|set-cookie|authorization|proxy-authorization|x-api-key|api-key)(\\s*:\\s*).*$","$1$2[REDACTED]").replaceAll("(?i)([?&](?:[^=&\\s]*(?:token|key|secret|password|auth)[^=&\\s]*)=)[^&\\s]+","$1[REDACTED]").replaceAll("(?i)(\"[^\"]*(?:token|secret|password|authorization|cookie|api.?key)[^\"]*\"\\s*:\\s*)\"(?:[^\"\\\\]|\\\\.)*\"","$1\"[REDACTED]\"").replaceAll("(?i)((?:^|&)(?:[^=&\\s]*(?:token|secret|password|api.?key)[^=&\\s]*)=)[^&\\s]*","$1[REDACTED]");}
    static String aiContext(List<NetworkRecord> records,boolean full,boolean sensitive){StringBuilder s=new StringBuilder();for(NetworkRecord r:records){String item=full?all(r):r.method+" "+r.url+" → "+r.status+" "+r.mime+" "+size(r.transferBytes)+" "+r.error;if(item.length()>20000)item=item.substring(0,20000)+"\n[Item truncated at 20,000 characters]";if(s.length()+item.length()>60000){s.append("\n[Context capped at 60,000 characters]");break;}s.append(item).append("\n\n");}return sensitive?s.toString():masked(s.toString());}
    static JSONArray headersArray(Map<String,String> h){JSONArray a=new JSONArray();for(Map.Entry<String,String> e:h.entrySet())a.put(NetworkRecorder.json("name",e.getKey(),"value",e.getValue()));return a;}
    static Map<String,String> headersMap(JSONArray a){Map<String,String> h=new TreeMap<>(String.CASE_INSENSITIVE_ORDER);if(a!=null)for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null)h.merge(o.optString("name"),o.optString("value"),(x,y)->x+"\n"+y);}return h;}
    static String har(List<NetworkRecord> records){JSONArray entries=new JSONArray();SimpleDateFormat date=new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",Locale.US);date.setTimeZone(TimeZone.getTimeZone("UTC"));for(NetworkRecord r:records){JSONObject req=NetworkRecorder.json("method",r.method,"url",r.url,"httpVersion",r.protocol,"headers",headersArray(r.requestHeaders),"cookies",new JSONArray(),"queryString",new JSONArray(),"headersSize",-1,"bodySize",r.requestBody.length);if(r.hasPostData||r.requestBody.length>0)try{req.put("postData",NetworkRecorder.json("mimeType",header(r.requestHeaders,"Content-Type"),"text",new String(r.requestBody,StandardCharsets.UTF_8)));}catch(JSONException ignored){}
        JSONObject content=NetworkRecorder.json("size",r.responseBody.length,"mimeType",r.mime,"text",Base64.getEncoder().encodeToString(r.responseBody),"encoding","base64");JSONObject response=NetworkRecorder.json("status",r.status,"statusText",r.statusText,"httpVersion",r.protocol,"headers",headersArray(r.responseHeaders),"cookies",new JSONArray(),"content",content,"redirectURL",header(r.responseHeaders,"Location"),"headersSize",-1,"bodySize",r.responseBody.length);double elapsed=Math.max(0,(r.finished-r.started)*1000);entries.put(NetworkRecorder.json("startedDateTime",date.format(new Date(r.time)),"time",elapsed,"request",req,"response",response,"cache",new JSONObject(),"timings",NetworkRecorder.json("send",0,"wait",elapsed,"receive",0),"serverIPAddress",r.remoteAddress,"_spaceBodyNote",r.responseBodyNote,"_spaceBrowserDecoded",r.browserDecoded,"_spaceError",r.error,"_spacePinned",r.pinned,"_spaceTiming",r.timing));}
        return NetworkRecorder.json("log",NetworkRecorder.json("version","1.2","creator",NetworkRecorder.json("name","Space Browser","version","1.1.0"),"entries",entries)).toString();}
    static List<NetworkRecord> importHar(String text) throws JSONException {JSONArray entries=new JSONObject(text).getJSONObject("log").getJSONArray("entries");List<NetworkRecord> out=new ArrayList<>();long total=0;for(int i=0;i<Math.min(entries.length(),2000);i++){JSONObject e=entries.getJSONObject(i),req=e.getJSONObject("request"),res=e.getJSONObject("response"),content=res.optJSONObject("content");NetworkRecord r=new NetworkRecord(i+1,"import-"+i,"");r.url=req.optString("url");r.finalUrl=r.url;r.method=req.optString("method");r.protocol=res.optString("httpVersion");r.status=res.optInt("status");r.statusText=res.optString("statusText");r.requestHeaders.putAll(headersMap(req.optJSONArray("headers")));r.responseHeaders.putAll(headersMap(res.optJSONArray("headers")));JSONObject post=req.optJSONObject("postData");if(post!=null){r.hasPostData=true;r.requestBody=post.optString("text").getBytes(StandardCharsets.UTF_8);}if(content!=null){r.mime=content.optString("mimeType");String body=content.optString("text");try{r.responseBody=content.optString("encoding").equals("base64")?Base64.getMimeDecoder().decode(body):body.getBytes(StandardCharsets.UTF_8);}catch(IllegalArgumentException x){r.responseBodyNote="Invalid HAR Base64";}}
        if(r.requestBody.length>NetworkRecorder.BODY_LIMIT)r.requestBody=Arrays.copyOf(r.requestBody,NetworkRecorder.BODY_LIMIT);if(r.responseBody.length>NetworkRecorder.BODY_LIMIT)r.responseBody=Arrays.copyOf(r.responseBody,NetworkRecorder.BODY_LIMIT);total+=r.requestBody.length+r.responseBody.length;if(total>NetworkRecorder.TOTAL_BODY_LIMIT){r.requestBody=new byte[0];r.responseBody=new byte[0];r.responseBodyNote="Import body budget reached";}else r.responseBodyNote=e.optString("_spaceBodyNote","Imported HAR body");r.browserDecoded=e.optBoolean("_spaceBrowserDecoded",true);r.error=e.optString("_spaceError");r.timing=e.optString("_spaceTiming");r.pinned=e.optBoolean("_spacePinned");r.finished=e.optDouble("time")/1000;r.transferBytes=content==null?0:content.optLong("size");r.complete=true;try{SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSX",Locale.US);r.time=f.parse(e.optString("startedDateTime")).getTime();}catch(Exception ignored){}out.add(r);}return out;}
}
