package com.space.browser;

import android.app.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.os.*;
import android.text.*;
import android.text.style.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.function.Supplier;

/** Native virtualized network inspector, shared by the tab and bottom-sheet presentations. */
final class NetworkInspector extends LinearLayout {
    private final MainActivity host;
    private final NetworkRecorder source;
    private final Supplier<List<NetworkRecorder>> sources;
    private final Runnable close;
    private final Handler ui=new Handler(Looper.getMainLooper());
    private final ExecutorService worker=Executors.newSingleThreadExecutor();
    private final ArrayList<Item> visible=new ArrayList<>();
    private final FrameLayout content;
    private final TextView status;
    private TextView heading;
    private LinearLayout controls;
    private ScrollView detailScroll;
    private String detailSignature="";
    private final EditText search;
    private Button pause;
    private final ListView list;
    private final BaseAdapter adapter;
    private final int ink,muted,bg,panel,accent;
    private Item selected,comparison;
    private boolean allTabs,errorsOnly,attached,refreshing,decode;
    private String query="",decoder="Auto",mode="Headers";
    private int section;
    private long lastRevision=-1;
    private int generation;
    static final class Item {final NetworkRecorder owner;final NetworkRecord record;Item(NetworkRecorder o,NetworkRecord r){owner=o;record=r;}}
    NetworkInspector(MainActivity host,NetworkRecorder source,Supplier<List<NetworkRecorder>> sources,Runnable close){
        super(host);this.host=host;this.source=source;this.sources=sources;this.close=close;
        boolean dark=host.devPrefs().getBoolean("dev_dark",host.devPrefs().getBoolean("dark",true));ink=dark?0xfff5f2ff:0xff201b32;muted=dark?0xff999eb4:0xff716982;bg=dark?0xff0b0d14:0xfff6f4fb;panel=dark?0xff171c29:0xffffffff;accent=dark?0xffb9a5ff:0xff7050cd;
        decode=host.devPrefs().getBoolean("dev_decode",true);setOrientation(VERTICAL);setBackgroundColor(bg);setPadding(dp(12),dp(8),dp(12),0);
        LinearLayout title=row();Button back=button("‹",()->{if(selected!=null){selected=null;showList();}else close.run();});back.setContentDescription("Close network inspector");title.addView(back,new LayoutParams(dp(44),dp(46)));heading=text("Network",23,true);title.addView(heading,new LayoutParams(0,-2,1));title.addView(button("✦ AI",()->ai(false)));addView(title);
        status=text("Connecting…",11,false);status.setTextColor(muted);status.setPadding(dp(4),dp(4),0,dp(8));addView(status);
        search=new EditText(host);search.setTextColor(ink);search.setHintTextColor(muted);search.setTextSize(14);search.setSingleLine();search.setHint("Search URL, headers or body");search.setContentDescription("Search network traffic");GradientDrawable searchBg=new GradientDrawable();searchBg.setColor(panel);searchBg.setCornerRadius(dp(14));search.setBackground(searchBg);search.setPadding(dp(14),0,dp(12),0);addView(search,new LayoutParams(-1,dp(48)));search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void afterTextChanged(Editable e){}public void onTextChanged(CharSequence s,int a,int b,int c){query=s.toString();generation++;lastRevision=-1;refresh();if(selected!=null)details();}});
        controls=row();pause=button("Pause",()->{boolean next=!source.paused();for(NetworkRecorder r:activeSources())r.pause(next);pause.setText(source.paused()?"Resume":"Pause");lastRevision=-1;});controls.addView(pause,new LayoutParams(0,dp(46),1));controls.addView(button("Clear",()->{for(NetworkRecorder r:activeSources())r.clear();selected=null;lastRevision=-1;showList();refresh();}),new LayoutParams(0,dp(46),1));controls.addView(button("More",this::more),new LayoutParams(0,dp(46),1));addView(controls);
        content=new FrameLayout(host);addView(content,new LayoutParams(-1,0,1));list=new ListView(host);list.setDividerHeight(dp(1));list.setCacheColorHint(bg);list.setClipToPadding(false);adapter=new BaseAdapter(){public int getCount(){return visible.size();}public Object getItem(int i){return visible.get(i);}public long getItemId(int i){return i;}public View getView(int i,View recycled,ViewGroup parent){LinearLayout cell=recycled instanceof LinearLayout?(LinearLayout)recycled:cell();Item item=visible.get(i);NetworkRecord r=item.record;((TextView)cell.getChildAt(0)).setText((r.pinned?"★ ":"")+r.method+"  "+r.type+"   #"+r.id);((TextView)cell.getChildAt(1)).setText(highlight(r.url));TextView meta=(TextView)cell.getChildAt(2);meta.setText((r.blocked?"BLOCKED":!r.error.isEmpty()?"FAILED":r.status==0?"Pending":String.valueOf(r.status))+"   "+NetworkFormats.size(r.transferBytes)+"   "+new java.text.SimpleDateFormat("HH:mm:ss",Locale.US).format(new Date(r.time))+(r.redirect?"  ↪":"")+(r.fromCache?"  Cache":"")+(!NetworkFormats.header(r.responseHeaders,"Content-Encoding").isEmpty()?"  Compressed":"")+(r.mime.contains("json")?"  { }":"")+(r.hasPostData?"  POST ▤":""));meta.setTextColor(r.blocked||!r.error.isEmpty()||r.status>=400?0xffec8592:r.status==0?muted:r.status>=300?0xff74b5ef:0xff60cdb2);return cell;}};list.setAdapter(adapter);list.setOnItemClickListener((p,v,pos,id)->{selected=visible.get(pos);section=0;mode="Headers";details();});list.setOnItemLongClickListener((p,v,pos,id)->{selected=visible.get(pos);actions();return true;});showList();
    }
    private int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    private TextView text(String s,int size,boolean bold){TextView t=new TextView(host);t.setText(s);t.setTextColor(ink);t.setTextSize(size);if(bold)t.setTypeface(Typeface.create("sans-serif-medium",Typeface.NORMAL));return t;}
    private LinearLayout row(){LinearLayout l=new LinearLayout(host);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    private LinearLayout column(){LinearLayout l=new LinearLayout(host);l.setOrientation(VERTICAL);return l;}
    private Button button(String s,Runnable action){Button b=new Button(host);b.setText(s);b.setTextColor(accent);b.setTextSize(12);b.setAllCaps(false);b.setMinWidth(0);b.setMinimumWidth(0);b.setPadding(dp(6),0,dp(6),0);GradientDrawable shape=new GradientDrawable();shape.setColor(panel);shape.setCornerRadius(dp(12));android.graphics.drawable.RippleDrawable ripple=new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(0x337f6ada),shape,null);b.setBackground(new android.graphics.drawable.InsetDrawable(ripple,dp(3),dp(3),dp(3),dp(3)));b.setElevation(0);b.setOnClickListener(v->action.run());return b;}
    private LinearLayout cell(){LinearLayout c=column();c.setPadding(dp(12),dp(13),dp(12),dp(13));c.setBackgroundColor(panel);TextView title=text("",13,true);title.setTextColor(accent);c.addView(title);TextView url=text("",14,false);url.setMaxLines(2);url.setPadding(0,dp(6),0,dp(6));c.addView(url);c.addView(text("",11,false));return c;}
    private List<NetworkRecorder> activeSources(){return allTabs?sources.get():Collections.singletonList(source);}
    private final Runnable ticker=new Runnable(){public void run(){if(!attached)return;refresh();ui.postDelayed(this,150);}};
    @Override protected void onAttachedToWindow(){super.onAttachedToWindow();attached=true;ui.post(ticker);}
    @Override protected void onDetachedFromWindow(){attached=false;ui.removeCallbacks(ticker);super.onDetachedFromWindow();}
    void dispose(){attached=false;ui.removeCallbacksAndMessages(null);worker.shutdownNow();}
    private void refresh(){if(refreshing||worker.isShutdown())return;long revision=0;List<NetworkRecorder> active=activeSources();for(NetworkRecorder r:active)revision+=r.revision();if(selected==null)status.setText(visible.size()+" items · "+(allTabs?"All tabs":source.state()));if(revision==lastRevision)return;lastRevision=revision;refreshing=true;String q=query;int g=generation;boolean errors=errorsOnly;worker.execute(()->{ArrayList<Item> results=new ArrayList<>();for(NetworkRecorder owner:active)for(NetworkRecord r:owner.snapshots())if((!errors||r.status>=400||!r.error.isEmpty())&&NetworkFormats.matches(r,q))results.add(new Item(owner,r));results.sort((a,b)->Long.compare(b.record.time,a.record.time));ui.post(()->{refreshing=false;if(g!=generation){lastRevision=-1;return;}visible.clear();visible.addAll(results);adapter.notifyDataSetChanged();if(selected==null)status.setText(visible.size()+" items · "+(allTabs?"All tabs":source.state()));else if(!signature(latest()).equals(detailSignature)){int y=detailScroll==null?0:detailScroll.getScrollY();details();detailScroll.post(()->detailScroll.scrollTo(0,y));}if(selected==null&&visible.isEmpty())showList();else if(selected==null&&list.getParent()==null)showList();});});}
    private void showList(){heading.setText("Network");search.setVisibility(VISIBLE);controls.setVisibility(VISIBLE);content.removeAllViews();if(visible.isEmpty()){TextView empty=text(query.isEmpty()?"Your page’s traffic appears here.\n\nOpen a site or reload it after enabling capture.":"No requests contain '"+query+"'.",16,false);empty.setGravity(Gravity.CENTER);empty.setTextColor(muted);content.addView(empty,new FrameLayout.LayoutParams(-1,-1));}else{if(list.getParent()!=null)((ViewGroup)list.getParent()).removeView(list);content.addView(list,new FrameLayout.LayoutParams(-1,-1));}}
    private CharSequence highlight(String value){SpannableString s=new SpannableString(value);if(query.isEmpty())return s;String lower=value.toLowerCase(Locale.ROOT),q=query.toLowerCase(Locale.ROOT);int index=0,count=0;while((index=lower.indexOf(q,index))>=0&&count++<1000){s.setSpan(new BackgroundColorSpan(0xff68541d),index,index+q.length(),Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);index+=q.length();}return s;}
    private NetworkRecord latest(){NetworkRecord r=selected.owner.get(selected.record.id);return r==null?selected.record:r;}
    private String signature(NetworkRecord r){return r.status+"|"+r.requestSize()+"|"+r.responseSize()+"|"+r.requestHeaders.hashCode()+"|"+r.responseHeaders.hashCode()+"|"+r.responseBodyNote+"|"+r.complete;}
    private void details(){if(selected==null)return;NetworkRecord r=latest();detailSignature=signature(r);heading.setText("Contents");status.setText(r.method+" · "+BrowserLogic.host(r.url)+" · #"+r.id);search.setVisibility(GONE);controls.setVisibility(GONE);content.removeAllViews();LinearLayout page=column();content.addView(page,new FrameLayout.LayoutParams(-1,-1));LinearLayout tabs=row();String[] names={"Overview","Request","Response"};for(int i=0;i<3;i++){final int index=i;Button b=button(names[i],()->{section=index;details();});if(section==i)b.setTextColor(ink);tabs.addView(b,new LayoutParams(0,dp(46),1));}page.addView(tabs);
        LinearLayout modes=row();for(String name:new String[]{"Headers","Text","Hex","Raw"}){Button b=button(name,()->{mode=name;details();});if(name.equals(mode))b.setTextColor(ink);modes.addView(b,new LayoutParams(0,dp(44),1));}
        ScrollView scroll=new ScrollView(host);detailScroll=scroll;LinearLayout body=column();scroll.addView(body);page.addView(scroll,new LayoutParams(-1,0,1));
        TextView output=text("",12,false);output.setTypeface(Typeface.MONOSPACE);output.setTextIsSelectable(true);output.setPadding(dp(8),dp(12),dp(8),dp(12));String value;
        if(section==0){value=overview(r);body.addView(output);if(!r.timing.isEmpty())body.addView(new TimingView(host,r,accent,muted),new LayoutParams(-1,dp(130)));}
        else {boolean request=section==1;byte[] bytes=request?r.requestBytes():r.responseBytes();if(mode.equals("Headers"))value=request?r.requestText():r.responseText();else if(mode.equals("Hex"))value=NetworkFormats.hex(bytes);else if(mode.equals("Raw"))value=NetworkFormats.raw(r,request);else value=NetworkFormats.body(r,request,decode,decoder);body.addView(output);
            if(!request&&mode.equals("Text")&&r.mime.startsWith("image/")&&bytes.length>0){BitmapFactory.Options options=new BitmapFactory.Options();options.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);options.inSampleSize=Math.max(1,Math.max(options.outWidth,options.outHeight)/1024);options.inJustDecodeBounds=false;Bitmap bitmap=BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);if(bitmap!=null){ImageView image=new ImageView(host);image.setImageBitmap(bitmap);image.setAdjustViewBounds(true);body.addView(image,new LayoutParams(-1,dp(220)));}}
            if(mode.equals("Text")&&decode){try{Object json=new JSONTokener(new String(bytes,java.nio.charset.StandardCharsets.UTF_8)).nextValue();if(json instanceof JSONObject||json instanceof JSONArray){Button tree=button("Explore JSON tree",()->jsonTree(json,"Root"));body.addView(tree);}}catch(Exception ignored){}}
        }
        if(value.length()>NetworkFormats.DISPLAY_LIMIT)value=value.substring(0,NetworkFormats.DISPLAY_LIMIT)+"\n[Display truncated; Save exports the retained body]";output.setText(syntax(value));
        if(section!=0)page.addView(modes);LinearLayout decodeRow=row();CheckBox enabled=new CheckBox(host);enabled.setText("Decode");enabled.setTextColor(ink);enabled.setChecked(decode);enabled.setOnCheckedChangeListener((v,on)->{decode=on;details();});decodeRow.addView(enabled);Spinner decoders=new Spinner(host);decoders.setAdapter(new ArrayAdapter<>(host,android.R.layout.simple_spinner_dropdown_item,NetworkFormats.DECODERS));decoders.setSelection(Arrays.asList(NetworkFormats.DECODERS).indexOf(decoder));decoders.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int pos,long id){String next=NetworkFormats.DECODERS[pos];if(!decoder.equals(next)){decoder=next;details();}}});decodeRow.addView(decoders,new LayoutParams(0,dp(46),1));decodeRow.addView(button("Actions",this::actions));page.addView(decodeRow);
        final float[] down={0};scroll.setOnTouchListener((v,e)->{if(e.getAction()==MotionEvent.ACTION_DOWN)down[0]=e.getX();if(e.getAction()==MotionEvent.ACTION_UP){float dx=e.getX()-down[0];if(Math.abs(dx)>dp(100)){section=Math.max(0,Math.min(2,section+(dx<0?1:-1)));details();}}return false;});
    }
    private CharSequence syntax(String value){SpannableString s=new SpannableString(highlight(value));if(section!=0&&mode.equals("Text")&&decode){java.util.regex.Matcher keys=java.util.regex.Pattern.compile("\"(?:[^\"\\\\]|\\\\.)*\"(?=\\s*:)").matcher(value);int count=0;while(keys.find()&&count++<2000)s.setSpan(new ForegroundColorSpan(accent),keys.start(),keys.end(),Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);java.util.regex.Matcher literals=java.util.regex.Pattern.compile("\\b(?:true|false|null|[0-9]+(?:\\.[0-9]+)?)\\b").matcher(value);count=0;while(literals.find()&&count++<2000)s.setSpan(new ForegroundColorSpan(0xff60cdb2),literals.start(),literals.end(),Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);}return s;}
    private String overview(NetworkRecord r){StringBuilder hops=new StringBuilder();for(NetworkRecord other:selected.owner.snapshots())if(other.requestId.equals(r.requestId)&&other.session.equals(r.session))hops.insert(0,other.status+" "+other.url+"\n");return r.method+" "+r.url+"\n\nStatus: "+r.status+" "+r.statusText+"\nFinal URL: "+(r.finalUrl.isEmpty()?r.url:r.finalUrl)+"\nProtocol: "+r.protocol+"\nType: "+r.type+"\nMIME: "+r.mime+"\nRemote address: "+(r.remoteAddress.isEmpty()?"Not exposed":r.remoteAddress)+"\nStarted: "+new Date(r.time)+"\nDuration: "+(r.complete?String.format(Locale.US,"%.1f ms",Math.max(0,(r.finished-r.started)*1000)):"In progress")+"\nTransferred: "+NetworkFormats.size(r.transferBytes)+"\nRequest body: "+NetworkFormats.size(r.requestSize())+"\nCaptured response: "+NetworkFormats.size(r.responseSize())+"\nCache: "+r.fromCache+"\nHeaders: "+(r.requestExtra?"Additional browser request headers captured":"Headers exposed by this WebView version")+"\n"+r.error+"\n\nRedirect chain / request\n"+hops+"\n"+r.responseBodyNote;}
    private void jsonTree(Object json,String title){ArrayList<String> names=new ArrayList<>();ArrayList<Object> values=new ArrayList<>();if(json instanceof JSONObject){Iterator<String> keys=((JSONObject)json).keys();while(keys.hasNext()&&names.size()<500){String key=keys.next();Object value=((JSONObject)json).opt(key);names.add(key+": "+summary(value));values.add(value);}}else if(json instanceof JSONArray){JSONArray a=(JSONArray)json;for(int i=0;i<Math.min(a.length(),500);i++){Object value=a.opt(i);names.add(i+": "+summary(value));values.add(value);}}new SpaceDialogBuilder(host).setTitle(title).setItems(names.toArray(new String[0]),(d,i)->{Object v=values.get(i);if(v instanceof JSONObject||v instanceof JSONArray)jsonTree(v,names.get(i));else showText(names.get(i),String.valueOf(v));}).setNegativeButton("Close",null).show();}
    private String summary(Object v){return v instanceof JSONObject?"{…}":v instanceof JSONArray?"[…]":String.valueOf(v).length()>150?String.valueOf(v).substring(0,150)+"…":String.valueOf(v);}
    private void showText(String title,String value){TextView out=text(value,12,false);out.setTextIsSelectable(true);out.setPadding(20,20,20,20);ScrollView scroll=new ScrollView(host);scroll.addView(out);new SpaceDialogBuilder(host).setTitle(title).setView(scroll).setPositiveButton("Close",null).show();}
    private void ai(boolean summaries){
        String[] options=selected==null?new String[]{"All captured requests","Current search results"}:new String[]{"Selected request — headers and bodies","All captured requests","Current search results"};
        new SpaceDialogBuilder(host).setTitle("Choose AI context").setItems(options,(d,index)->{ArrayList<NetworkRecord> records=new ArrayList<>();String option=options[index];boolean full=option.startsWith("Selected");if(full)records.add(latest());else if(option.startsWith("All"))for(NetworkRecorder recorder:activeSources())records.addAll(recorder.snapshots());else for(Item item:visible)records.add(item.record);new SpaceAi(host).show(records,full);}).show();
    }
    private void actions(){if(selected==null)return;NetworkRecord r=latest();String[] names={"Copy URL","Copy headers","Copy body","Copy entire item","Copy as cURL","Copy as Fetch","Copy as Python",r.pinned?"Unpin":"Pin (keep when cleared)","Save body","Share item","Send to AI","Edit and resend",comparison==null?"Select for comparison":"Compare with selected item","Refresh details","Save item as HAR"};new SpaceDialogBuilder(host).setTitle(r.method+" · "+r.status).setItems(names,(d,i)->{boolean request=section==1;switch(i){case 0:host.copyText(r.url);break;case 1:host.copyText(NetworkRecord.headers(request?r.requestHeaders:r.responseHeaders));break;case 2:host.copyText(NetworkFormats.body(r,request,decode,decoder));break;case 3:host.copyText(NetworkFormats.all(r));break;case 4:host.copyText(NetworkFormats.curl(r));break;case 5:host.copyText(NetworkFormats.fetch(r));break;case 6:host.copyText(NetworkFormats.python(r));break;case 7:selected.owner.pin(r.id);lastRevision=-1;details();break;case 8:host.saveDevFile(request?r.requestBytes():r.responseBytes(),"space-body-"+r.id+".bin","application/octet-stream");break;case 9:host.startActivity(android.content.Intent.createChooser(new android.content.Intent(android.content.Intent.ACTION_SEND).setType("text/plain").putExtra(android.content.Intent.EXTRA_TEXT,NetworkFormats.all(r)),"Share captured item"));break;case 10:ai(false);break;case 11:replay(r);break;case 12:if(comparison==null){comparison=selected;host.devToast("Select another request to compare");}else{NetworkRecord other=comparison.record;showComparison(other,r);comparison=null;}break;case 13:details();break;case 14:host.saveDevFile(NetworkFormats.har(Collections.singletonList(r)).getBytes(java.nio.charset.StandardCharsets.UTF_8),"space-request.har","application/json");break;}}).show();}
    private void showComparison(NetworkRecord a,NetworkRecord b){
        LinearLayout columns=row();columns.setGravity(Gravity.TOP);String[] left=NetworkFormats.all(a).split("\n"),right=NetworkFormats.all(b).split("\n");LinearLayout l=column(),r=column();l.setPadding(12,12,12,12);r.setPadding(12,12,12,12);l.setBackgroundColor(panel);r.setBackgroundColor(bg);l.addView(text("A · #"+a.id,15,true));r.addView(text("B · #"+b.id,15,true));
        int length=Math.min(300,Math.max(left.length,right.length));for(int i=0;i<length;i++){String x=i<left.length?left[i]:"",y=i<right.length?right[i]:"";TextView lt=text(x,11,false),rt=text(y,11,false);lt.setTypeface(Typeface.MONOSPACE);rt.setTypeface(Typeface.MONOSPACE);lt.setTextIsSelectable(true);rt.setTextIsSelectable(true);if(!x.equals(y)){lt.setTextColor(0xffec8592);rt.setTextColor(0xff60cdb2);}l.addView(lt);r.addView(rt);}columns.addView(l,new LayoutParams(dp(300),-2));columns.addView(r,new LayoutParams(dp(300),-2));HorizontalScrollView horizontal=new HorizontalScrollView(host);horizontal.addView(columns);ScrollView scroll=new ScrollView(host);scroll.addView(horizontal);new SpaceDialogBuilder(host).setTitle("Compare · changed lines in colour").setMessage("Headers and bodies, first 300 lines. Scroll sideways for both columns.").setView(scroll).setPositiveButton("Close",null).show();
    }
    private void more(){String[] names={allTabs?"Show this tab":"Show all tabs",errorsOnly?"Show all statuses":"Errors and blocked only","Export filtered HAR","Export all HAR","Import HAR","Developer tools settings","Ask AI about listed requests"};new SpaceDialogBuilder(host).setTitle("Network options").setItems(names,(d,i)->{switch(i){case 0:allTabs=!allTabs;lastRevision=-1;generation++;refresh();break;case 1:errorsOnly=!errorsOnly;lastRevision=-1;generation++;refresh();break;case 2:export(true);break;case 3:export(false);break;case 4:host.importDevHar();break;case 5:settings();break;case 6:ai(true);break;}}).show();}
    private void export(boolean filtered){List<NetworkRecord> records=new ArrayList<>();if(filtered)for(Item item:visible)records.add(item.record);else for(NetworkRecorder r:activeSources())records.addAll(r.snapshots());host.saveDevFile(NetworkFormats.har(records).getBytes(java.nio.charset.StandardCharsets.UTF_8),"space-network.har","application/json");}
    private void settings(){LinearLayout form=column();form.setPadding(20,10,20,10);Switch popup=new Switch(host);popup.setText("Open tools in a popup");popup.setChecked(host.devPrefs().getBoolean("dev_popup",false));form.addView(popup);Switch capture=new Switch(host);capture.setText("Capture enabled by default");capture.setChecked(host.devPrefs().getBoolean("dev_capture",true));form.addView(capture);Switch masking=new Switch(host);masking.setText("Mask sensitive AI context");masking.setChecked(host.devPrefs().getBoolean("dev_mask",true));form.addView(masking);Switch auto=new Switch(host);auto.setText("Auto-decode bodies");auto.setChecked(host.devPrefs().getBoolean("dev_decode",true));form.addView(auto);Switch dark=new Switch(host);dark.setText("Dark inspector");dark.setChecked(host.devPrefs().getBoolean("dev_dark",host.devPrefs().getBoolean("dark",true)));form.addView(dark);EditText maximum=new EditText(host);maximum.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);maximum.setHint("Maximum requests (50–2000)");maximum.setText(String.valueOf(host.devPrefs().getInt("dev_limit",2000)));form.addView(maximum);TextView note=text("Capture uses this app’s WebView debugger. Authorized ADB clients can also inspect it while enabled. Bodies over 64 kB use private cache files. Capture retains up to 2 MiB per body and 12 MiB per tab. Theme/presentation changes apply on reopening.",12,false);form.addView(note);new SpaceDialogBuilder(host).setTitle("Developer tools").setView(form).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{int limit;try{limit=Math.max(50,Math.min(2000,Integer.parseInt(maximum.getText().toString())));}catch(Exception e){limit=2000;}host.devPrefs().edit().putBoolean("dev_popup",popup.isChecked()).putBoolean("dev_mask",masking.isChecked()).putBoolean("dev_decode",auto.isChecked()).putBoolean("dev_dark",dark.isChecked()).putInt("dev_limit",limit).apply();for(NetworkRecorder recorder:sources.get())recorder.setLimit(limit);host.setCapture(capture.isChecked());decode=auto.isChecked();}).show();}
    private void replay(NetworkRecord original){LinearLayout form=column();EditText url=new EditText(host);url.setText(original.url);form.addView(url);EditText method=new EditText(host);method.setText(original.method);method.setSingleLine();form.addView(method);EditText headers=new EditText(host);headers.setText(NetworkRecord.headers(original.requestHeaders));headers.setMaxLines(5);form.addView(headers);EditText body=new EditText(host);body.setText(new String(original.requestBytes(),java.nio.charset.StandardCharsets.UTF_8));body.setMaxLines(5);form.addView(body);ScrollView scroll=new ScrollView(host);scroll.addView(form);new SpaceDialogBuilder(host).setTitle("Edit and resend").setMessage("Send a NEW request to this URL. This can change server data. Redirects are shown without following them; it uses the headers below.").setView(scroll).setNegativeButton("Cancel",null).setPositiveButton("Send request",(d,w)->{NetworkRecord edited=new NetworkRecord(System.currentTimeMillis(),"replay","");edited.url=url.getText().toString();edited.method=method.getText().toString().trim().toUpperCase(Locale.ROOT);for(String line:headers.getText().toString().split("\n")){int colon=line.indexOf(':');if(colon>0)edited.requestHeaders.put(line.substring(0,colon).trim(),line.substring(colon+1).trim());}edited.requestBody=body.getText().toString().getBytes(java.nio.charset.StandardCharsets.UTF_8);host.replayDevRequest(edited,source);}).show();}
    private static final class TimingView extends View {
        private final NetworkRecord record;private final int accent,muted;private final Paint paint=new Paint(3);
        TimingView(android.content.Context c,NetworkRecord r,int a,int m){super(c);record=r;accent=a;muted=m;}
        @Override protected void onDraw(Canvas canvas){try{JSONObject t=new JSONObject(record.timing);String[] labels={"DNS","Connect","TLS","TTFB","Download"};double[][] times={{t.optDouble("dnsStart",-1),t.optDouble("dnsEnd",-1)},{t.optDouble("connectStart",-1),t.optDouble("connectEnd",-1)},{t.optDouble("sslStart",-1),t.optDouble("sslEnd",-1)},{t.optDouble("sendEnd",-1),t.optDouble("receiveHeadersStart",-1)},{t.optDouble("receiveHeadersEnd",-1),Math.max(0,(record.finished-record.started)*1000)}};double max=1;for(double[] range:times)max=Math.max(max,range[1]);float density=getResources().getDisplayMetrics().density,left=90*density;paint.setTextSize(11*density);for(int i=0;i<labels.length;i++){float y=(i*24+18)*density;paint.setColor(muted);canvas.drawText(labels[i]+(times[i][0]<0?" n/a":""),4*density,y,paint);if(times[i][0]>=0&&times[i][1]>=times[i][0]){paint.setColor(accent);canvas.drawRect(left+(float)(times[i][0]/max)*(getWidth()-left),y-9*density,left+(float)(times[i][1]/max)*(getWidth()-left)+2,y,paint);}}}catch(Exception ignored){}}
    }
}
